/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Seccion Nocturna
 */
public class Matematic extends javax.swing.JFrame {

    /**
     * Creates new form Matematic
     */
    public Matematic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buton4 = new javax.swing.JToggleButton();
        buton3 = new javax.swing.JToggleButton();
        buton2 = new javax.swing.JToggleButton();
        buton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Convertidor de unidades.");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 270, 30));

        buton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buton4.setText("De usos");
        buton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton4ActionPerformed(evt);
            }
        });
        getContentPane().add(buton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, -1));

        buton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buton3.setText("De Tipo");
        buton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton3ActionPerformed(evt);
            }
        });
        getContentPane().add(buton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, -1));

        buton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buton2.setText("De magnitud");
        buton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton2ActionPerformed(evt);
            }
        });
        getContentPane().add(buton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));

        buton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buton1.setText("Empezar");
        buton1.setEnabled(false);
        buton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton1ActionPerformed(evt);
            }
        });
        getContentPane().add(buton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1552143173.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton2ActionPerformed
        if(buton2.isSelected()){
            if(buton4.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton3.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
        else{
                  if(buton3.isSelected()){
                     if(buton2.isSelected()){
                         buton1.setEnabled(false);
                         }
                     else if(buton4.isSelected()){
                         buton1.setEnabled(false);
                         }
                      else{
                         buton1.setEnabled(true);
                          }
                     }
                  else if(buton4.isSelected()){
            if(buton2.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton3.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
        else{
            buton1.setEnabled(false);
        }
        }
    }//GEN-LAST:event_buton2ActionPerformed

    private void buton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton3ActionPerformed
        if(buton3.isSelected()){
            if(buton4.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton2.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
        else{
           if(buton2.isSelected()){
            if(buton4.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton3.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
           else if(buton4.isSelected()){
            if(buton2.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton3.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
        else{
            buton1.setEnabled(false);
        }
        }
    }//GEN-LAST:event_buton3ActionPerformed

    private void buton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton4ActionPerformed
        if(buton4.isSelected()){
            if(buton2.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton3.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
        else{
                  if(buton3.isSelected()){
                     if(buton2.isSelected()){
                         buton1.setEnabled(false);
                         }
                     else if(buton4.isSelected()){
                         buton1.setEnabled(false);
                         }
                      else{
                         buton1.setEnabled(true);
                          }
                     }
                  else if(buton2.isSelected()){
            if(buton4.isSelected()){
                buton1.setEnabled(false);
            }
            else if(buton3.isSelected()){
                buton1.setEnabled(false);
            }
            else{
            buton1.setEnabled(true);
            }
        }
        else{
            buton1.setEnabled(false);
        }
        }
    }//GEN-LAST:event_buton4ActionPerformed

    private void buton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton1ActionPerformed
        if(buton2.isSelected()){
            Matematic1 verformulario2=new Matematic1();
            verformulario2.setVisible(true);
        }
        else if(buton3.isSelected()){
            Matematic2 verformulario2=new Matematic2();
            verformulario2.setVisible(true);           
        }
        else if(buton4.isSelected()){
            Matematic3 verformulario2=new Matematic3();
            verformulario2.setVisible(true);           
        }     
    }//GEN-LAST:event_buton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matematic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matematic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matematic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matematic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matematic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buton1;
    private javax.swing.JToggleButton buton2;
    private javax.swing.JToggleButton buton3;
    private javax.swing.JToggleButton buton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
